export const ACTIONS = {
  LOGOUT: "LOGOUT",
  SET_LOADER: "SET_LOADER",
  LOGIN: "LOGIN",
  FETCH_LOGIN_DATA: "FETCH_LOGIN_DATA",

  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  GET_SINGLE_USER: "GET_SINGLE_USER",
  SET_SINGLE_USER: "SET_SINGLE_USER",

  CHANGE_LAYOUT: "CHANGE_LAYOUT",
  CHANGE_LAYOUT_WIDTH: "CHANGE_LAYOUT_WIDTH",
  CHANGE_SIDEBAR_THEME: "CHANGE_SIDEBAR_THEME",
  CHANGE_SIDEBAR_TYPE: "CHANGE_SIDEBAR_TYPE",

  // topbar
  CHANGE_TOPBAR_THEME: "CHANGE_TOPBAR_THEME",

  // show sidebar
  SHOW_SIDEBAR: "SHOW_SIDEBAR",
  TOGGLE_LEFTMENU: "TOGGLE_LEFTMENU",

  /* RIGHT SIDEBAR */
  SHOW_RIGHT_SIDEBAR: "SHOW_RIGHT_SIDEBAR",

  // ONLINE USERS
  SET_ONLINE_USERS: "SET_ONLINE_USERS",
  ADD_ONLINE_USER: "ADD_ONLINE_USER",
  REMOVE_ONLINE_USER: "REMOVE_ONLINE_USER",

  SUBMIT_FIREBASE_TOKEN: "SUBMIT_FIREBASE_TOKEN",
}
